### ISSUE TITLE
Hatalı işleme tıklarsam?

### ISSUE THREAD

**Issue by cosane** [bozburak/PyQt5_Calculator#1]
Selamlar Burakcım,

Ya hatalı bir işleme tıklarsam? Mesela 3 yazdım, sonra +'ya bastım ama aslında 3-1 yapmak istiyordum. Hadi bakalım, şimdi ne yapacağız? Denemesi bedava, aç bir hesap makinesi, 3 yaz, +'ya bas, sonra -'ye bas, sonra 1'e bas, sonuç 2 çıkar. Oysa seninki hata veriyor.

**Comment by bozburak** [comment]
Bunun içinde koşullu ifade kullanmam gerektiğini düşünüyorum.
Programı güncelleyeceğim.

**Comment by bozburak** [comment]
Güncelleme!
179-206 Kod Satırları Düzenlendi.
Hata giderildi.
