### ISSUE TITLE
İlk işlemden sonra yeni işlem istersem?

### ISSUE THREAD

**Issue by cosane** [bozburak/PyQt5_Calculator#2]
İlk işlemi başarıyla bitirip yeni bir işlem yapmak istediğimde eski sonucun arkasına yazılıyor. Mesela 3+1 yaptım 4 çıktı, şimdi 2+3 yapacağım ama 2'ye basar basmaz 42 oluyor ;)

**Comment by bozburak** [comment]
Hatalı işlem ve bu gibi hataları sil tuşu ekliyerek gidereceğim.

**Comment by bozburak** [comment]
Program Güncellendi!
Temizle butonu eklendi.

**Comment by cosane** [comment]
Sil de lazım Ama burada gereken sil düğmesi düğmesi
Değil. = sonrası bir rakama tıklandığı anda varolan silinmeli ;)

29 Ara 2017 Cum, saat 23:56 tarihinde bozburak <notifications@github.com>
şunu yazdı:

**Comment by bozburak** [comment]
def bir(self):
        if self.sonucbtn.isChecked() == True:
            self.ekran.setText("")
            self.ekran.setText(self.ekran.text() + "1"
        else :
            self.ekran.setText(self.ekran.text() + "1")

Eğer sonuc butonuna tıklanmışşa texti sil sonra 1 yaz tıklanmamışsa birşey varsa yanına 1 yaz komutu bu olmalı isChecked Tıklanmışmı diye 2 değer döndürmeli True False Olarak eğer Doğruysa tıklandıysa komutlarımı uygulaması gerekiyor ancak koşulun içindekilere bakmıyor daha doğrusu koşula girmiyor. 
Sebebi ne olabilir hocam.

**Comment by bozburak** [comment]
Program Güncellendi..!
Belirttiginiz Hata Giderildi.
