### ISSUE TITLE
Ben klavye kullanmayı seviyorum.

### ISSUE THREAD

**Issue by cosane** [bozburak/PyQt5_Calculator#3]
Ben tıklamayı değil, yazmayı seviyorum ama senin program benim tuşlarımı algılamıyor. Sadece tıklama ile çalışıyor. Ne yapsak acaba?

**Comment by bozburak** [comment]
Klavye kütüphanesini import edip programı geliştirdikten sonra sizi buradan haberdar edeceğim.
Önerileriniz için teşekkürler.

**Comment by bozburak** [comment]
Program Güncellendi!
Yardımlarınız İçin Teşekkür Ederim Hocam.
