### ISSUE TITLE
setGeometry'den vazgeç

### ISSUE THREAD

**Issue by cosane** [bozburak/PyQt5_Calculator#5]
Burakcım setGeometry konusunu önceden konuşmuştuk sen de pencereyi kilitlediğini, boyut değişmediğini söylemiştin ama bu haliyle kod güzel olmuyor. Izgara kullanımı bunun için ideal. hLayout ve vLayaout ile baştan oluştur derim.

**Comment by bozburak** [comment]
Hocam h ve l layout ile baştan oluşturdum ama hoşuma gitmedi.
Sebebi
Tam ekran yaptığımızda enine büyüyor ancak boyuna büyümüyor.(-_-_-_-_-_-)

**Comment by bozburak** [comment]
Enine büyümeyince bende setgeometryden vazgeçtim ancak setfixed dan vaz geçmedim :)
