### ISSUE TITLE
işlev, işlev, işlev

### ISSUE THREAD

**Issue by cosane** [bozburak/PyQt5_Calculator#6]
Program bu haliyle oldukça eksik. Unutma, **print("boz")** demeyi bilen biri on defa bunu yazsa ekrana on defa "boz" yazar. Oysa biraz daha bilgili olan biri **for x in range(10):** diyerek işi bilgisayara yaptırır.

Düğmeleri oluşturduğun kısımları tek bir fonksiyon ile oluştur ve düğmelere görev atadığın, her biri ayrı ayrı olan fonksiyonları da rakam fonksiyonu adıyla yeni bir fonksiyon oluşturarak, bu fonksiyona gönderilen parametreyle işlem yap. Mesela rakam(x) çalıştırıldığında x adlı düğmeyi çalıştır. rakam(1) 1'i çalıştırır, rakam(9) 9'u.

En az 110-120 tane kadar satır azalır.

Hadi bakalım.

**Comment by bozburak** [comment]
Teşekkürler Hocam.
