### ISSUE TITLE
Yeni kod

### ISSUE THREAD

**Issue by cosane** [bozburak/PyQt5_Calculator#7]
__author__ = "Burak BOZ"
import sys
from PyQt5.QtWidgets import QWidget, QPushButton, QLineEdit, QApplication, QVBoxLayout, QHBoxLayout

class hesap_makinesi(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Hesap Makinesi")
        self.setFixedWidth(270)
        self.setFixedHeight(220)
        self.hesap = ""
        self.islemyapilmismi = ""
        self.tiklanmismi = ""
        self.dugmeler = [x for x in range(10)]

        """ Pencere Yerleşimleri """
        self.ana = QVBoxLayout(self)
        self.lineedit = QHBoxLayout(self)
        self.bir_iki_uc_geri = QHBoxLayout(self)
        self.dort_bes_alti_sil = QHBoxLayout(self)
        self.yedi_sekiz_dokuz_enter = QHBoxLayout(self)
        self.arti_eksi_carp_bol = QHBoxLayout(self)
        self.sifirr = QHBoxLayout(self)
        self.kesirr = QHBoxLayout(self)

        self.ana.addLayout(self.lineedit)
        self.ana.addLayout(self.bir_iki_uc_geri)
        self.ana.addLayout(self.dort_bes_alti_sil)
        self.ana.addLayout(self.yedi_sekiz_dokuz_enter)
        self.ana.addLayout(self.arti_eksi_carp_bol)
        self.ana.addLayout(self.sifirr)
        self.ana.addLayout(self.kesirr)

        """ İşlem Butonlarının Ayarları """
        self.ekran = QLineEdit(self)
        self.ekran.setReadOnly(True)

        self.geribtn = QPushButton(self)
        self.geribtn.setText("←")
        self.geribtn.setShortcut("Backspace")

        self.silbtn = QPushButton(self)
        self.silbtn.setText("C")
        self.silbtn.setShortcut("Del")

        self.sonucbtn = QPushButton(self)
        self.sonucbtn.setText("⏎")
        self.sonucbtn.setShortcut("Return")

        self.artibtn = QPushButton(self)
        self.artibtn.setText("+")
        self.artibtn.setShortcut("+")

        self.eksibtn = QPushButton(self)
        self.eksibtn.setText("-")
        self.eksibtn.setShortcut("-")

        self.carpbtn = QPushButton(self)
        self.carpbtn.setText("*")
        self.carpbtn.setShortcut("*")

        self.bolbtn = QPushButton(self)
        self.bolbtn.setText("/")
        self.bolbtn.setShortcut("/")

        self.kesirbtn = QPushButton(self)
        self.kesirbtn.setText(".")
        self.kesirbtn.setShortcut(".")

        self.lineedit.addWidget(self.ekran)
        self.bir_iki_uc_geri.addWidget(self.geribtn)
        self.dort_bes_alti_sil.addWidget(self.silbtn)
        self.yedi_sekiz_dokuz_enter.addWidget(self.sonucbtn)
        self.kesirr.addWidget(self.kesirbtn)
        self.arti_eksi_carp_bol.addWidget(self.artibtn)
        self.arti_eksi_carp_bol.addWidget(self.eksibtn)
        self.arti_eksi_carp_bol.addWidget(self.carpbtn)
        self.arti_eksi_carp_bol.addWidget(self.bolbtn)

        """
        İşlev atama işi sadece tek satırdan oluştuğu halde neden bunu
        ayrı bir fonksiyon haline getirdiğimi merak edebilirsin.
        Epeydir bu sorunla uğraşıyorum. Denemesi bedava:
        Aşağıdaki döngüde islev_ata fonksiyonunu çağırmak yerine
        self.dugmeler[i].clicked.connect(lambda: self.islev(str(i)))
        şeklinde kullan bak ne oluyor. Tüm tuşlar tek rakamı basıyor.
        Bu önceden bir yerde okuduğum, Python'un döngüleri döndürürkenki
        bir tutumundan kaynaklanıyor. Bunu hatırladım. Python self.islev(...)
        yazan yeri sırasıyla 0,1,2... diye algılamuyor, her seferinde
        bu döngü bittiği zamanki i'nin son değerini kullanıyor. Ama fonksiyon
        çağırıp i'yi bu fonksiyona yollarsak her seferinde o anki i değerini
        yolluyor :) Sebebini okumuştum ama aramama rağmen kaynağı şu anda
        bulamadım. O yüzden islev_ata adında fonksiyon var ve her i değeri
        bu fonksiyona yollanıyor.
        """
        def islev_ata(sayi):
            """
            Bunu da yeni öğrendim, eğer fonksiyona self'den başka bir argüman
            yollamak istiyorsak lambda:'dan sonra bu fonksiyona seslenmemiz
            gerekiyormuş. Diğer türlü boş argüman hatası alıyoruz.
            """
            self.dugmeler[sayi].clicked.connect(lambda: self.islev(str(sayi)))

        """ Sayı Butonlarının Ayarları """
        for i in range(10):
            self.dugmeler[i] = QPushButton(self)
            self.dugmeler[i].setText(str(i))
            self.dugmeler[i].setShortcut(str(i))
            islev_ata(i)

        #Buralarda sen hep dugmeler[i] demişsin ama i dönmüyor ki :))
        self.bir_iki_uc_geri.addWidget(self.dugmeler[1])
        self.bir_iki_uc_geri.addWidget(self.dugmeler[2])
        self.bir_iki_uc_geri.addWidget(self.dugmeler[3])
        self.dort_bes_alti_sil.addWidget(self.dugmeler[4])
        self.dort_bes_alti_sil.addWidget(self.dugmeler[5])
        self.dort_bes_alti_sil.addWidget(self.dugmeler[6])
        self.yedi_sekiz_dokuz_enter.addWidget(self.dugmeler[7])
        self.yedi_sekiz_dokuz_enter.addWidget(self.dugmeler[8])
        self.yedi_sekiz_dokuz_enter.addWidget(self.dugmeler[9])
        self.sifirr.addWidget(self.dugmeler[0])

        """ Butonlara Tıklandığında Çalıştıracakları Fonksiyonlar """
        self.artibtn.clicked.connect(self.toplama)
        self.eksibtn.clicked.connect(self.cikarma)
        self.carpbtn.clicked.connect(self.carpma)
        self.bolbtn.clicked.connect(self.bolme)
        self.silbtn.clicked.connect(self.silme)
        self.geribtn.clicked.connect(self.geri)
        self.kesirbtn.clicked.connect(self.kesir)
        self.sonucbtn.clicked.connect(self.sonuc)

    """ Sayı Fonksiyonları """
    def islev(self, rakam):
        if self.islemyapilmismi == "evet":
            self.ekran.setText("")
            self.ekran.setText(self.ekran.text() + str(rakam))
            self.islemyapilmismi = ""
        else:
            self.ekran.setText(self.ekran.text() + str(rakam))

    """ İslem Fonksiyonları """
    def toplama(self):
        self.hesap = "+"
        if self.ekran.text() == "":
            self.ekran.setText(str(self.ilksayi))
        self.ilksayi = float(self.ekran.text())
        self.ekran.setText("")
        self.tiklanmismi = "ikinci"

    def cikarma(self):
        self.hesap = "-"
        if self.ekran.text() == "":
            self.ekran.setText(str(self.ilksayi))
        self.ilksayi = float(self.ekran.text())
        self.ekran.setText("")
        self.tiklanmismi = "ikinci"

    def carpma(self):
        self.hesap = "*"
        if self.ekran.text() == "":
            self.ekran.setText(str(self.ilksayi))
        self.ilksayi = float(self.ekran.text())
        self.ekran.setText("")
        self.tiklanmismi = "ikinci"

    def bolme(self):
        self.hesap = "/"
        if self.ekran.text() == "":
            self.ekran.setText(str(self.ilksayi))
        self.ilksayi = float(self.ekran.text())
        self.ekran.setText("")
        self.tiklanmismi = "ikinci"

    def silme(self):
        self.ekran.clear()
        self.tiklanmismi = "silme"
    def geri(self):
        self.ekran.backspace()
        self.tiklanmismi = "geri"

    def kesir(self):
        if self.ekran.text() == "":
            self.ekran.setText("")
        elif self.islemyapilmismi == "evet":
            self.ekran.setText("")
            self.islemyapilmismi = ""
        else:
            if self.tiklanmismi == "evet":
                self.ekran.setText(self.ekran.text())
            elif self.tiklanmismi == "ikinci":
                self.ekran.setText(self.ekran.text() + ".")
                self.tiklanmismi = "evet"
            elif self.tiklanmismi == "silme":
                self.ekran.setText(self.ekran.text() + ".")
                self.tiklanmismi = "evet"
            elif self.tiklanmismi == "geri":
                self.ekran.setText(self.ekran.text() + ".")
                self.tiklanmismi = "evet"
            else:
                self.ekran.setText(self.ekran.text() + ".")
                self.tiklanmismi = "evet"

    """ Sonuc Fonksiyonu """
    def sonuc(self):
        if self.hesap == "":
            self.ekran.setText("İşlem Yapmadınız!")
        else:
            self.ikincisayi = float(self.ekran.text())
            if self.hesap == "+":
                self.islem = self.ilksayi + self.ikincisayi
                if self.islem == int(self.islem):
                    self.ekran.setText(str(int(self.islem)))
                elif self.islem == float(self.islem):
                    self.ekran.setText(str(float(self.islem)))
            elif self.hesap == "-":
                self.islem = self.ilksayi - self.ikincisayi
                if self.islem == int(self.islem):
                    self.ekran.setText(str(int(self.islem)))
                elif self.islem == float(self.islem):
                    self.ekran.setText(str(float(self.islem)))
            elif self.hesap == "*":
                self.islem = self.ilksayi * self.ikincisayi
                if self.islem == int(self.islem):
                    self.ekran.setText(str(int(self.islem)))
                elif self.islem == float(self.islem):
                    self.ekran.setText(str(float(self.islem)))
            elif self.hesap == "/":
                if self.ikincisayi == 0:
                    self.ekran.setText("HATA")
                else:
                    self.islem = self.ilksayi / self.ikincisayi
                    if self.islem == int(self.islem):
                        self.ekran.setText(str(int(self.islem)))
                    elif self.islem == float(self.islem):
                        self.ekran.setText(str(float(self.islem)))
        self.islemyapilmismi = "evet"
        self.tiklanmismi = ""

uygulama = QApplication(sys.argv)
pencere = hesap_makinesi()
pencere.show()
uygulama.exec_()

**Comment by bozburak** [comment]
Teşekkürler Hocam
